### PR TITLE
docs: StarkGate

### PR DESCRIPTION
**Pull request by ArielElp**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] Docs have been updated
- [ ] PR title is follow the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

---
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/23)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/23)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp)

___
*[docs/L1<>L2 Communication/token-bridge.md, line 15 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/23#-N-XrqNw0fK3qtVwdAj1:-N-XrqNw0fK3qtVwdAj2:b-2aau94) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/9b88ca705944def9a2ed27045dff50c3ef46925d/docs/L1%3C%3EL2%20Communication/token-bridge.md#L15)):*
> ```Markdown
> The user calls the function `deposit` (see [ERC-20 deposit](https://github.com/starkware-libs/starkgate-contracts/blob/28f4032b101003b2c6682d753ea61c86b732012c/src/starkware/starknet/apps/starkgate/solidity/StarknetERC20Bridge.sol#L10) and [ETH deposit](https://github.com/starkware-libs/starkgate-contracts/blob/28f4032b101003b2c6682d753ea61c86b732012c/src/starkware/starknet/apps/starkgate/solidity/StarknetEthBridge.sol#L10)), supplying as parameters the recipient address on StarkNet and the amount to transfer in the case of ERC-20 token. The deposit function then:
> 
> - Checks that the funds transferred are within the Alpha limitations
> ```

maybe link to the limitations section below as it is not mentioned before.
___
*[docs/L1<>L2 Communication/token-bridge.md, line 17 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/23#-N-Xs4OKEZqrj5wFR48s:-N-Xs4OKEZqrj5wFR48t:b-b6g8g5) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/9b88ca705944def9a2ed27045dff50c3ef46925d/docs/L1%3C%3EL2%20Communication/token-bridge.md#L17)):*
> ```Markdown
> - Checks that the funds transferred are within the Alpha limitations
> - Transfers the funds from the user account to the StarkNet bridge
> - Emits a deposit event with the sender address on L1, the recipient address on L2, and the amount
> ```

link to the event on the code?
___
*[docs/L1<>L2 Communication/token-bridge.md, line 20 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/23#-N-XsCXhEJCyn7FeSpKT:-N-XsCXhEJCyn7FeSpKU:bk5yy3x) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/9b88ca705944def9a2ed27045dff50c3ef46925d/docs/L1%3C%3EL2%20Communication/token-bridge.md#L20)):*
> ```Markdown
> - Sends a message to the relevant L2 bridge with the amount to be transferred, and the recipient address as parameters. Note that, since every single bridge is dedicated to one token type, the token type doesn't have to be explicit here.
> 
> At the end of this step (i.e., after the execution on L1) the deposit transaction is known to StarkNet’s sequencer, yet sequencers may wait for enough L1 confirmations before corresponding deposit transaction is initated on L2. At this step, the status of the deposit request will be [`NOT_RECEIVED`](../Blocks/transaction-life-cycle#not_received)
> ```

It's unclear that you mean the status of the L2 transaction consuming the message.
I suggest removing this sentence or explaining it better.



_Code quote:_
```Markdown
At this step, the status of the deposit request will be 
```
___
*[docs/L1<>L2 Communication/token-bridge.md, line 54 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/23#-N-XtF-E8j_-pvajw2Ig:-N-XtF-E8j_-pvajw2Ih:b3xc99y) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/9b88ca705944def9a2ed27045dff50c3ef46925d/docs/L1%3C%3EL2%20Communication/token-bridge.md#L54)):*
> ```Markdown
> :::
> 
> ## StarkGate Alpha Limitations
> ```

Here let's have a table that indicates exactly what are the limitations.
If the limitations are for the ETH bridge, we should specify what is the exact amount.
It should be very easy to understand the exact numbers and to update them.

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/23)* status: all files reviewed, 4 unresolved discussions (waiting on @bbrandtom)

___
*[docs/L1<>L2 Communication/token-bridge.md, line 15 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/23#-N-XrqNw0fK3qtVwdAj1:-N0-iREj4AAeDB2sXZFE:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/9b88ca705944def9a2ed27045dff50c3ef46925d/docs/L1%3C%3EL2%20Communication/token-bridge.md#L15)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

maybe link to the limitations section below as it is not mentioned before.
</blockquote></details>

Done.
___
*[docs/L1<>L2 Communication/token-bridge.md, line 17 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/23#-N-Xs4OKEZqrj5wFR48s:-N0-ishV0Qrul8Hl9KNe:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/9b88ca705944def9a2ed27045dff50c3ef46925d/docs/L1%3C%3EL2%20Communication/token-bridge.md#L17)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

link to the event on the code?
</blockquote></details>

Done.
___
*[docs/L1<>L2 Communication/token-bridge.md, line 20 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/23#-N-XsCXhEJCyn7FeSpKT:-N0-jdb4DtWQ0P1zWall:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/9b88ca705944def9a2ed27045dff50c3ef46925d/docs/L1%3C%3EL2%20Communication/token-bridge.md#L20)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

It's unclear that you mean the status of the L2 transaction consuming the message.
I suggest removing this sentence or explaining it better.
</blockquote></details>

Done.
___
*[docs/L1<>L2 Communication/token-bridge.md, line 54 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/23#-N-XtF-E8j_-pvajw2Ig:-N0-jpkT2AaKeKlPmXxp:btj0frn) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/9b88ca705944def9a2ed27045dff50c3ef46925d/docs/L1%3C%3EL2%20Communication/token-bridge.md#L54)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Here let's have a table that indicates exactly what are the limitations.
If the limitations are for the ETH bridge, we should specify what is the exact amount.
It should be very easy to understand the exact numbers and to update them.
</blockquote></details>

There are two parameters which are currently covered by two points, so I don't think there's a need for a table. Once we have more tokens, I think it's more readable to avoid writing limitations in terms of individual tokens, but only keep the $ limit (even just for ETH, I don't see much additional value in writing e.g. 23542531252364264364363463 wei).

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/23)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`docs/L1<>L2 Communication/token-bridge.md` line 54 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/23#-N-XtF-E8j_-pvajw2Ig:-N0it1vJ9E03OQg2chgr:bi7tocn) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/9b88ca705944def9a2ed27045dff50c3ef46925d/docs/L1%3C%3EL2%20Communication/token-bridge.md#L54)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

There are two parameters which are currently covered by two points, so I don't think there's a need for a table. Once we have more tokens, I think it's more readable to avoid writing limitations in terms of individual tokens, but only keep the $ limit (even just for ETH, I don't see much additional value in writing e.g. 23542531252364264364363463 wei).
</blockquote></details>

But the $ value can change drastically, so it has no meaning.
Let's talk f2f on this.

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/23)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bbrandtom)

___
*[`docs/L1<>L2 Communication/token-bridge.md` line 54 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/23#-N-XtF-E8j_-pvajw2Ig:-N0yiKUX8JiMrO-eAqrg:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/9b88ca705944def9a2ed27045dff50c3ef46925d/docs/L1%3C%3EL2%20Communication/token-bridge.md#L54)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

But the $ value can change drastically, so it has no meaning.
Let's talk f2f on this.
</blockquote></details>

Done.

**Review by bbrandtom — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/23#-:-N0z4dWp5NVdHjwo-lLn:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
