### PR TITLE
docs: events

### PR DESCRIPTION
**Pull request by ArielElp**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Check List

- [ ] Changes have been done against master branch, and PR does not conflict
- [ ] New unit / functional tests have been added (whenever applicable)
- [ ] Test are passing in local environment
- [ ] Docs have been updated
- [ ] PR title is follow the convention: `<type>[optional scope]: <description>`, e.g: `fix: minor typos in code`

---
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/14)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/14)* status: all files reviewed, 6 unresolved discussions (waiting on @ArielElp)

___
*[docs/Events/starknet-events.md, line 1 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-Jw094ZDLZmVyQwxp:-Mx-Jw094ZDLZmVyQwxq:b-ewi07p) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L1)):*
> ```Markdown
> # StarkNet Events
> ```

Remove the name "StarkNet"
___
*[docs/Events/starknet-events.md, line 13 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-K-hlC4Uv8pk7QP4b:-Mx-K-hlC4Uv8pk7QP4c:b6kp9de) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L13)):*
> ```Markdown
> ## Emitting events
> 
> Events can be defined in a contract using the `@event` decorator. Once an event $E$ has been defined, the compiler automatically adds the function `E.emit()`. The following example illustrates how an event is defined and then emitted:
> ```

$E$ - > `E`

"...and then emitted:" -> remove "then"
___
*[docs/Events/starknet-events.md, line 15 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-LNzqEdQiPbBzb9xC:-Mx-LNzqEdQiPbBzb9xD:b7vod0d) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L15)):*
> ```Markdown
> Events can be defined in a contract using the `@event` decorator. Once an event $E$ has been defined, the compiler automatically adds the function `E.emit()`. The following example illustrates how an event is defined and then emitted:
> 
> ```js
> ```

do we highlight cairo code with js syntax? maybe python?
___
*[docs/Events/starknet-events.md, line 25 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-KuQ611rKrvQV8oQF:-Mx-KuQ611rKrvQV8oQG:bj1y8d) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L25)):*
> ```Markdown
> ```
> 
> The emit function emits an event with a single key, which is an identifier of the event, given by $\text{sn\_keccak(event\_name)}$, where $\text{event\_name}$ is the ASCII encoding of the event’s name and $\text{sn\_keccak}$ is defined [here](../Hashing/hash-functions#starknet-keccak). To emit custom keys, one should use the low level `emit_event` [system call](https://github.com/starkware-libs/cairo-lang/blob/ed6cf8d6cec50a6ad95fa36d1eb4a7f48538019e/src/starkware/starknet/common/syscalls.cairo#L301), which takes an array of keys and an array of data as input.
> ```

I don't think we should link here to a specific code.
Either we add the explanation or we remove it and add it as some other point.



_Code quote:_
```Markdown
To emit custom keys, one should use the low level `emit_event` [system call](https://github.com/starkware-libs/cairo-lang/blob/ed6cf8d6cec50a6ad95fa36d1eb4a7f48538019e/src/starkware/starknet/common/syscalls.cairo#L301), which takes an array of keys and an array of data as input.
```
___
*[docs/Events/starknet-events.md, line 27 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-L6nD1OjXjlfOlBj6:-Mx-L6nD1OjXjlfOlBj7:b59ji9n) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L27)):*
> ```Markdown
> The emit function emits an event with a single key, which is an identifier of the event, given by $\text{sn\_keccak(event\_name)}$, where $\text{event\_name}$ is the ASCII encoding of the event’s name and $\text{sn\_keccak}$ is defined [here](../Hashing/hash-functions#starknet-keccak). To emit custom keys, one should use the low level `emit_event` [system call](https://github.com/starkware-libs/cairo-lang/blob/ed6cf8d6cec50a6ad95fa36d1eb4a7f48538019e/src/starkware/starknet/common/syscalls.cairo#L301), which takes an array of keys and an array of data as input.
> 
> Note that the emit function may take structs or arrays (with an adjacent parameter indicating the array’s length) as arguments, which will be flattened into a single array of felts.
> ```

consider giving an example
consider writing this as a callout or writing explicitly what arguments are acceptable.
___
*[docs/Events/starknet-events.md, line 66 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-Kd348zqzxxpRVSaN:-Mx-Kd354L4zWI0G-VYi:bqkk3vd) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L66)):*
> ```Markdown
> - $h$ is the [pedersen](../Hashing/hash-functions#pedersen-hash) hash function
> 
> The event hashes are eventually included in the [event_commitment](../Blocks/header#event_commitment) field of a block.
> ```

remove "eventually"

event_commitment as code

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/14)* status: all files reviewed, 5 unresolved discussions (waiting on @bbrandtom)

___
*[docs/Events/starknet-events.md, line 1 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-Jw094ZDLZmVyQwxp:-Mx-nmMg-8148KjLgk7F:be4gsul) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L1)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Remove the name "StarkNet"
</blockquote></details>

If the name is events then we have:
Events
   Events
In the left side navigation bar, which is weird. I'll take different suggestions for names (name for this page or name for the category)
___
*[docs/Events/starknet-events.md, line 13 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-K-hlC4Uv8pk7QP4b:-Mx-moFl3qYo4F4JBmV1:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L13)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

$E$ - > `E`

"...and then emitted:" -> remove "then"
</blockquote></details>

Done.
___
*[docs/Events/starknet-events.md, line 15 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-LNzqEdQiPbBzb9xC:-Mx-mre_0dCkNnwilSgB:by8sa70) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L15)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

do we highlight cairo code with js syntax? maybe python?
</blockquote></details>

python doesn't work well here, I just used what I could get most colors of
___
*[docs/Events/starknet-events.md, line 25 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-KuQ611rKrvQV8oQF:-Mx-rDlX-oxzBZCYEJGB:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L25)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I don't think we should link here to a specific code.
Either we add the explanation or we remove it and add it as some other point.
</blockquote></details>

Done.
___
*[docs/Events/starknet-events.md, line 27 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-L6nD1OjXjlfOlBj6:-Mx-tbuZ-GsaH_2KX-M2:bb6un1j) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L27)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

consider giving an example
consider writing this as a callout or writing explicitly what arguments are acceptable.
</blockquote></details>

Done
___
*[docs/Events/starknet-events.md, line 66 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-Kd348zqzxxpRVSaN:-Mx-ndeI8RsguGLJq__w:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L66)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

remove "eventually"

event_commitment as code
</blockquote></details>

Done.

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/14)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[docs/Events/starknet-events.md, line 1 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-Jw094ZDLZmVyQwxp:-Mx009pkE3JS_-UUGiO7:bbg1hwk) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L1)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

If the name is events then we have:
Events
   Events
In the left side navigation bar, which is weird. I'll take different suggestions for names (name for this page or name for the category)

</blockquote></details>

Yes, I understand. But right now it looks a bit strange. We might want to think about how to make it better. e.g - remove the folder and just have it as a file in the root dir
___
*[docs/Events/starknet-events.md, line 15 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-LNzqEdQiPbBzb9xC:-Mx01oHWB3Z6SXdDTdNm:bft99ng) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L15)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

python doesn't work well here, I just used what I could get most colors of
</blockquote></details>

ok, please add an issue to add python/cairo synthax highlighting
___
*[docs/Events/starknet-events.md, line 66 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-Kd348zqzxxpRVSaN:-Mx09amf6T_KjE6tEE2V:b-gy5hq2) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L66)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Done.
</blockquote></details>

remove "eventually"
___
*[docs/Events/starknet-events.md, line 30 at r2](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx09OZ_81lfph2FuKz9:-Mx09OZ_81lfph2FuKzA:b-ip587h) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/478442eb896a33c83a303f0c7b6f74adeb5fbac3/docs/Events/starknet-events.md#L30)):*
> ```Markdown
> from starkware.starknet.common.syscalls import emit_event
> 
> # ...
> ```

why do we have this?
same for above
___
*[docs/Events/starknet-events.md, line 43 at r2](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx02sBb0Xa1T5yduhT3:-Mx02sBb0Xa1T5yduhT4:undefined) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/478442eb896a33c83a303f0c7b6f74adeb5fbac3/docs/Events/starknet-events.md#L43)):*
> ```Markdown
> 
> The above code emits an event with two keys, the [strings](https://www.cairo-lang.org/docs/how_cairo_works/consts.html#short-string-literals) "status" and "deposit" (think of those as identifiers
> of the event that you might like to filter over in the future) and three data elments 1, 2, 3.
> ```





_Suggestion:_
```Markdown
that can be used to index the event
```
___
*[docs/Events/starknet-events.md, line 46 at r2](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx09VTuCnJOYNkNw7Yu:-Mx09VTuCnJOYNkNw7Yv:b-7ilvfu) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/478442eb896a33c83a303f0c7b6f74adeb5fbac3/docs/Events/starknet-events.md#L46)):*
> ```Markdown
> 
> :::tip
> When using the higher level `emit` syntax, the event's data may of of complex types, for example:
> ```

typo?



_Code quote:_
```Markdown
 may of of complex
```

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/14)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[docs/Events/starknet-events.md, line 66 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-Kd348zqzxxpRVSaN:-Mx0D6fq6ODVdisCouxk:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L66)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

remove "eventually"
</blockquote></details>

Done.
___
*[docs/Events/starknet-events.md, line 30 at r2](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx09OZ_81lfph2FuKz9:-Mx0CK2q7k-GBkIO9_m-:b4vlpft) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/478442eb896a33c83a303f0c7b6f74adeb5fbac3/docs/Events/starknet-events.md#L30)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

why do we have this?
same for above
</blockquote></details>

To emphasize this isn't copy pastable, you need context (that's what were currently doing in hello starknet)
___
*[docs/Events/starknet-events.md, line 43 at r2](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx02sBb0Xa1T5yduhT3:-Mx0CzxW-SrVdpKhZjU5:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/478442eb896a33c83a303f0c7b6f74adeb5fbac3/docs/Events/starknet-events.md#L43)):*
> ```Markdown
> 
> The above code emits an event with two keys, the [strings](https://www.cairo-lang.org/docs/how_cairo_works/consts.html#short-string-literals) "status" and "deposit" (think of those as identifiers
> of the event that you might like to filter over in the future) and three data elments 1, 2, 3.
> ```

Done.

**Review by bbrandtom — DISMISSED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-:-Mx3Z8hZ0z2Glt5L8dDK:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

___
*[docs/Events/starknet-events.md, line 1 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/14#-Mx-Jw094ZDLZmVyQwxp:-Mx3Z4rl1NIe4kzzPeVd:bo70jwo) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/236592e9288ef7026ed325382142e89668680402/docs/Events/starknet-events.md#L1)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Yes, I understand. But right now it looks a bit strange. We might want to think about how to make it better. e.g - remove the folder and just have it as a file in the root dir
</blockquote></details>

Will be solved in a seperate PR

**Pull request merged**
