### PR TITLE
docs: data availability 

### PR DESCRIPTION
**Pull request by dan-ziv**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Check List

- [ ] Changes have been done against master branch, and PR does not conflict
- [ ] New unit / functional tests have been added (whenever applicable)
- [ ] Test are passing in local environment
- [ ] Docs have been updated
- [ ] PR title is follow the convention: `<type>[optional scope]: <description>`, e.g: `fix: minor typos in code`

---
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/9)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/9)* status: 0 of 2 files reviewed, 11 unresolved discussions (waiting on @bbrandtom and @dan-ziv)

___
*[docs/DataAvailabilty/on-chain-data.md, line 11 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgA9foEdUsDdV24XN2:-MwgA9foEdUsDdV24XN3:bbz2sl1) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L11)):*
> ```Markdown
> ## Format
> 
> The state diffs contain information on every contact whose storage was updated and additional information on contract deployments. Those differences are sent as `unit256[]` array as part of the calldata, that is encoded as follows:
> ```

@bbrandtom that -> and

done
___
*[docs/DataAvailabilty/on-chain-data.md, line 17 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgBL5ABtrQbXsTsaRO:-MwgBL5ABtrQbXsTsaRP:b2a20vs) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L17)):*
> ```Markdown
>   - `contract_address` - the [address](../Contracts/contract-address) of the deployed contract
>   - `contract_hash` - the [hash](../Contracts/contract-hash) of the contract
>   - `len(call_data)` - number of arguments to the contract constructor
> ```

@bbrandtom 
call_data
or change to calldata above

Also, consider changing to something that reflects the fact it is the ctr arguments, as calldata is generic to all of the data that is being sent on L1.

Done
___
*[docs/DataAvailabilty/on-chain-data.md, line 18 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgC6nB-S72Ntjuj-4-:-MwgC6nB-S72Ntjuj-40:bdc4zqa) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L18)):*
> ```Markdown
>   - `contract_hash` - the [hash](../Contracts/contract-hash) of the contract
>   - `len(call_data)` - number of arguments to the contract constructor
>   - `calldata` - list of arguments to the constructors
> ```

@bbrandtom 
constructors - constructor

Done 
___
*[docs/DataAvailabilty/on-chain-data.md, line 19 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgDX9I8qj_22jiprKv:-MwgDX9I8qj_22jiprKw:b-sl4pcb) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L19)):*
> ```Markdown
>   - `len(call_data)` - number of arguments to the contract constructor
>   - `calldata` - list of arguments to the constructors
> - Number of contracts whose stroage is updated
> ```

@bbrandtom stroage

Done
___
*[docs/DataAvailabilty/on-chain-data.md, line 20 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgCzDI7JpIGBekAIKE:-MwgCzDI7JpIGBekAIKF:b-llt3vy) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L20)):*
> ```Markdown
>   - `calldata` - list of arguments to the constructors
> - Number of contracts whose stroage is updated
> - For each such contract, we have:
> ```

@bbrandtom I think we are missing the address here

Done
___
*[docs/DataAvailabilty/on-chain-data.md, line 23 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgCHwZ8DVtbBEubAzS:-MwgCHwZ8DVtbBEubAzT:b-k7ny29) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L23)):*
> ```Markdown
>   - `num_of_storage_updates` - number of storage updates
>   - For each storage update:
>     - `address` - the address inside the contract's stroage where the value is updated
> ```

@bbrandtom storage

Done
___
*[docs/DataAvailabilty/on-chain-data.md, line 23 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgDd7h2NcGa1lhU4Kt:-MwgDd7i0ZjvGfz73SVx:bh0typd) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L23)):*
> ```Markdown
>   - `num_of_storage_updates` - number of storage updates
>   - For each storage update:
>     - `address` - the address inside the contract's stroage where the value is updated
> ```

@bbrandtom 

Do we call this address? I think it is a bit confusing with the contract address, consider either adding something that mentions storage or changing to key.

changed to key
___
*[docs/DataAvailabilty/on-chain-data.md, line 27 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgEVE-CgeZUOOIlBQF:-MwgEVE-CgeZUOOIlBQG:b95h4ds) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L27)):*
> ```Markdown
> 
> ## Example
> ```

@bbrandtom  Add a sentence before or after the JSON that explains what are we going to do.
something like - "We give an example of the on-chain data of a specific state update and explain each element"

Doneeth
___
*[docs/DataAvailabilty/on-chain-data.md, line 96 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgEz-V6YSAXBkyobYI:-MwgEz-V6YSAXBkyobYJ:b239wzh) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L96)):*
> ```Markdown
> ## Extract from Ethereum
> 
> The data described above is sent across several Etherum transactions, each holding a part of this array as calldata. Each new StarkNet block has its associated state diff transactions. You may find the code for extracting this data from Ethereum in [Pathfinder's repo](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/src/ethereum/state_update/retrieve.rs). Pathfinder is the first StarkNet full node implementation, whose alpha version is planned for the begininnig of March 2022. You may also take a look at the [python script](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/resources/fact_retrieval.py) which extracts the same information.
> ```

@bbrandtom Ethereum 

Done
___
*[docs/DataAvailabilty/on-chain-data.md, line 96 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgFI93ExsLxrVC3LTu:-MwgFI93ExsLxrVC3LTv:b-1mwmoi) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L96)):*
> ```Markdown
> ## Extract from Ethereum
> 
> The data described above is sent across several Etherum transactions, each holding a part of this array as calldata. Each new StarkNet block has its associated state diff transactions. You may find the code for extracting this data from Ethereum in [Pathfinder's repo](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/src/ethereum/state_update/retrieve.rs). Pathfinder is the first StarkNet full node implementation, whose alpha version is planned for the begininnig of March 2022. You may also take a look at the [python script](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/resources/fact_retrieval.py) which extracts the same information.
> ```

@bbrandtom begininnig

Done



_Code quote:_
```Markdown
begin
```
___
*[docs/DataAvailabilty/on-chain-data.md, line 96 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgFpFsBb2bIhXwnMtn:-MwgFpFsBb2bIhXwnMto:bq33jv2) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L96)):*
> ```Markdown
> ## Extract from Ethereum
> 
> The data described above is sent across several Etherum transactions, each holding a part of this array as calldata. Each new StarkNet block has its associated state diff transactions. You may find the code for extracting this data from Ethereum in [Pathfinder's repo](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/src/ethereum/state_update/retrieve.rs). Pathfinder is the first StarkNet full node implementation, whose alpha version is planned for the begininnig of March 2022. You may also take a look at the [python script](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/resources/fact_retrieval.py) which extracts the same information.
> ```

@bbrandtom Please remove mentions of specific dates in the docs.

Done



_Code quote:_
```Markdown
March 2022
```

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/9)* status: all files reviewed, 11 unresolved discussions (waiting on @ArielElp and @dan-ziv)

___
*[docs/DataAvailabilty/on-chain-data.md, line 96 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgFpFsBb2bIhXwnMtn:-MwgMPTnACJsk0FOJSm5:bdysbe4) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L96)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

@bbrandtom Please remove mentions of specific dates in the docs.

Done
</blockquote></details>

I meant to remove the fact that it will be released or anything like that. Just keep the sentence up to the ","

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/9)* status: all files reviewed, 1 unresolved discussion (waiting on @bbrandtom)

___
*[docs/DataAvailabilty/on-chain-data.md, line 96 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-MwgFpFsBb2bIhXwnMtn:-Mwtn2KC6keNlWRfzXdL:bb6un1j) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/ff36ef20b83276a5cb3abc67c25dc931a288eff9/docs/DataAvailabilty/on-chain-data.md#L96)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I meant to remove the fact that it will be released or anything like that. Just keep the sentence up to the ","
</blockquote></details>

Done

**Review by bbrandtom — DISMISSED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-:-MwuZTf901BVW1QGqR87:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-ziv)

**Review by ArielElp — DISMISSED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/9#-:-Mwupetw0v1BUot3YAF1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-ziv)

**Review by bbrandtom — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-ziv)

**Pull request merged**
