### PR TITLE
docs: starknet state

### PR DESCRIPTION
**Pull request by ArielElp**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Check List

- [ ] Changes have been done against master branch, and PR does not conflict
- [ ] New unit / functional tests have been added (whenever applicable)
- [ ] Test are passing in local environment
- [ ] Docs have been updated
- [ ] PR title is follow the convention: `<type>[optional scope]: <description>`, e.g: `fix: minor typos in code`

---
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/12)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/12)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[docs/State/starknet-state.md, line 10 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-Mx-NQf53IgCG82JsHns:-Mx-NQf53IgCG82JsHnt:b-619cu7) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/d39f8a7477eabbd84a04a7631831d113ce4a51f4/docs/State/starknet-state.md#L10)):*
> ```Markdown
> - [Contract storage](../Contracts/contract-storage) (a key-value mapping where the key/values are field elements)
> 
> With the above definition, we can provide a brief sketch of StarkNet’s transition function. A transaction $tx$ transitions the system from state $S$ to state $S’$ if:
> ```

it seems like you require those two conditions to hold, which they can't obviously
___
*[docs/State/starknet-state.md, line 29 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-Mx-T8h95kT9-p07YkqC:-Mx-T8h95kT9-p07YkqD:bew9892) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/d39f8a7477eabbd84a04a7631831d113ce4a51f4/docs/State/starknet-state.md#L29)):*
> ```Markdown
> - $h$ is the [Pedersen](../Hashing/hash-functions#pedersen-hash) hash function.
> 
> ### Merkle-Patricia tree
> ```

make Heading 1
___
*[docs/State/starknet-state.md, line 31 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-Mx-TAUHBU-L9n9404Np:-Mx-TAUHBU-L9n9404Nq:bew9893) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/d39f8a7477eabbd84a04a7631831d113ce4a51f4/docs/State/starknet-state.md#L31)):*
> ```Markdown
> ### Merkle-Patricia tree
> 
> #### Specifications
> ```

make Heading 2
___
*[docs/State/starknet-state.md, line 53 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-Mx-T6r1A3d6RjfX7GUz:-Mx-T6r20xgw8oUOFvqT:b-7m74ox) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/d39f8a7477eabbd84a04a7631831d113ce4a51f4/docs/State/starknet-state.md#L53)):*
> ```Markdown
> $left=(\ell_L, p_L, b_L)$, $right=(\ell_R, p_R, b_R)$ is given by:
> 
> $$
> ```

nice!
___
*[docs/State/starknet-state.md, line 63 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-Mx-TCej-fMJoaNUHTMO:-Mx-TCej-fMJoaNUHTMP:bew9893) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/d39f8a7477eabbd84a04a7631831d113ce4a51f4/docs/State/starknet-state.md#L63)):*
> ```Markdown
> $$
> 
> #### Example Trie
> ```

make Heading 2

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/12)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @bbrandtom)

___
*[docs/State/starknet-state.md, line 10 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-Mx-NQf53IgCG82JsHns:-Mx-m30k9nc9cUv2TaaF:b-cxdqmu) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/d39f8a7477eabbd84a04a7631831d113ce4a51f4/docs/State/starknet-state.md#L10)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

it seems like you require those two conditions to hold, which they can't obviously
</blockquote></details>

I was thinking more like computation model syntax, I specify the transition function (each line is another possible behavior)
___
*[docs/State/starknet-state.md, line 29 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-Mx-T8h95kT9-p07YkqC:-Mx-uYVB3h1AmKJg1n0X:bvt3cro) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/d39f8a7477eabbd84a04a7631831d113ce4a51f4/docs/State/starknet-state.md#L29)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

make Heading 1
</blockquote></details>

but this is under the commitment
___
*[docs/State/starknet-state.md, line 31 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-Mx-TAUHBU-L9n9404Np:-Mx-ucno1c8ppIxWAW6q:b-e73955) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/d39f8a7477eabbd84a04a7631831d113ce4a51f4/docs/State/starknet-state.md#L31)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

make Heading 2
</blockquote></details>

this is under the merkle patricia tree
___
*[docs/State/starknet-state.md, line 53 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-Mx-T6r1A3d6RjfX7GUz:-Mx-mUAfACzQbd1MrUNY:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/d39f8a7477eabbd84a04a7631831d113ce4a51f4/docs/State/starknet-state.md#L53)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

nice!
</blockquote></details>

Done.
___
*[docs/State/starknet-state.md, line 63 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-Mx-TCej-fMJoaNUHTMO:-Mx-ulXQ0qVqzRb_JTNh:b-njehj6) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/d39f8a7477eabbd84a04a7631831d113ce4a51f4/docs/State/starknet-state.md#L63)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

make Heading 2
</blockquote></details>

Same hierarchy as specifications

**Review by bbrandtom — DISMISSED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-:-Mx0AFEP3CozA5ij80EF:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

___
*[docs/State/starknet-state.md, line 10 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-Mx-NQf53IgCG82JsHns:-Mx0ABuT4Ag9QAxCKMlU:b-w70003) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/d39f8a7477eabbd84a04a7631831d113ce4a51f4/docs/State/starknet-state.md#L10)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I was thinking more like computation model syntax, I specify the transition function (each line is another possible behavior)
</blockquote></details>

not familiar with it, but I trust you.
___
*[docs/State/starknet-state.md, line 29 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/12#-Mx-T8h95kT9-p07YkqC:-Mx0A3rOAk_qFRskorsT:b-gla8ms) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/d39f8a7477eabbd84a04a7631831d113ce4a51f4/docs/State/starknet-state.md#L29)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

but this is under the commitment
</blockquote></details>

it just looks strange..

**Review by ArielElp — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
