### PR TITLE
on chain data

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/1)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/1)* status: all files reviewed, 17 unresolved discussions (waiting on @ArielElp)

___
*[website/docs/DataAvailability/on-chain-data.md, line 3 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMruX5-drqteXNj_TX:-MwMruX5-drqteXNj_TY:b8n3v0f) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L3)):*
> ```Markdown
> # On-Chain Data
> 
> ## Introduction
> ```

Missing what is explained in this section - we explain here the format of the calldata that is posted on L1.
___
*[website/docs/DataAvailability/on-chain-data.md, line 7 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMrdZ5AyGpOUWgj67t:-MwMrdZ5AyGpOUWgj67u:b-gmdcg) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L7)):*
> ```Markdown
> In the current stage of the Alpha, StarkNet operates in a ZK-Rollup mode. This means that upon the acceptance of a state update on-chain, the state diff between the previous and new state is sent as calldata to Ethereum.
> 
> This data allows anyone that observes Ethereum to reconstruct the current state of StarkNet. Note that to update the StarkNet state on L1, it suffices to send a valid proof – without information on the transactions or particular changes that this update caused. Consequently, more information must be provided in order to allow other parties to locally track StarkNet’s state.
> ```

Not sure exactly what you're trying to say in this paragraph
___
*[website/docs/DataAvailability/on-chain-data.md, line 11 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMs5Ka778GA6YAKj8E:-MwMs5Ka778GA6YAKj8F:b-sbrnvk) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L11)):*
> ```Markdown
> ## Format
> 
> The state diffs contain information on every contact whose storage was updated and additional information on contract deployments. Those differences are sent as `unit256[]` array as part of the calldata, that is  encoded as follows:
> ```

that - >and



_Code quote:_
```Markdown
that
```
___
*[website/docs/DataAvailability/on-chain-data.md, line 11 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsADy2I6nNKGW_J28:-MwMsADy2I6nNKGW_J29:bnvjx0u) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L11)):*
> ```Markdown
> ## Format
> 
> The state diffs contain information on every contact whose storage was updated and additional information on contract deployments. Those differences are sent as `unit256[]` array as part of the calldata, that is  encoded as follows:
> ```

remove double space
___
*[website/docs/DataAvailability/on-chain-data.md, line 13 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsDOX1Zh5CScTWCa7:-MwMsDOX1Zh5CScTWCa8:bnpdlz0) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L13)):*
> ```Markdown
> The state diffs contain information on every contact whose storage was updated and additional information on contract deployments. Those differences are sent as `unit256[]` array as part of the calldata, that is  encoded as follows:
> 
> * Number of cells that encode contract deployments
> ```

I suggest giving a name to each variable - not clear when a name is given and when not.
Also, do those names reflect something in the code?
___
*[website/docs/DataAvailability/on-chain-data.md, line 17 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsPxP2IdXqLolfu26:-MwMsPxP2IdXqLolfu27:b-tmgu8f) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L17)):*
> ```Markdown
>   * `contract_address` - the [address](../Contracts/contract-address) of the deployed contract
>   * `contract_hash` - the [hash](../Contracts/contract-hash) of the contract
>   * `len(call_data)` - number of arguments to the contract constructor
> ```

missing "the" at the beginning of the sentence,
same belown
___
*[website/docs/DataAvailability/on-chain-data.md, line 18 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMpULYAEwJ0NyTMdbq:-MwMpULYAEwJ0NyTMdbr:b-ibt715) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L18)):*
> ```Markdown
>   * `contract_hash` - the [hash](../Contracts/contract-hash) of the contract
>   * `len(call_data)` - number of arguments to the contract constructor
>   * `calldata` - list of arguments to the constructors
> ```

`call_data`
or change to `calldata` above

Also, consider changing to something that reflects the fact it is the ctr arguments, as calldata is generic to all of the data that is being sent on L1.



_Code quote:_
```Markdown
calldata
```
___
*[website/docs/DataAvailability/on-chain-data.md, line 18 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsWRK2AcLvB9547Pq:-MwMsWRK2AcLvB9547Pr:b-tqriz) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L18)):*
> ```Markdown
>   * `contract_hash` - the [hash](../Contracts/contract-hash) of the contract
>   * `len(call_data)` - number of arguments to the contract constructor
>   * `calldata` - list of arguments to the constructors
> ```

constructors - constructor
___
*[website/docs/DataAvailability/on-chain-data.md, line 19 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMpRDb2Si5SHWcFzlw:-MwMpRDb2Si5SHWcFzlx:b4dhtqu) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L19)):*
> ```Markdown
>   * `len(call_data)` - number of arguments to the contract constructor
>   * `calldata` - list of arguments to the constructors
> * Number of contracts whose stroage is updated
> ```

storage



_Code quote:_
```Markdown
stroage
```
___
*[website/docs/DataAvailability/on-chain-data.md, line 20 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMs_fj-ollveLouG-d:-MwMs_fj-ollveLouG-e:b54x6xl) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L20)):*
> ```Markdown
>   * `calldata` - list of arguments to the constructors
> * Number of contracts whose stroage is updated
> * For each such contract, we have:
> ```

I think we are missing the address here
___
*[website/docs/DataAvailability/on-chain-data.md, line 23 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMpSv00WTQExq5bhhf:-MwMpSv00WTQExq5bhhg:b4dhtqu) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L23)):*
> ```Markdown
>   * `num_of_storage_updates` - number of storage updates
>   * For each storage update:
>     * `address` - the address inside the contract's stroage where the value is updated
> ```

storage



_Code quote:_
```Markdown
stroage
```
___
*[website/docs/DataAvailability/on-chain-data.md, line 23 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMseCw-xqqHj8UFgyd:-MwMseCw-xqqHj8UFgye:b-ur29by) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L23)):*
> ```Markdown
>   * `num_of_storage_updates` - number of storage updates
>   * For each storage update:
>     * `address` - the address inside the contract's stroage where the value is updated
> ```

Do we call this address? I think it is a bit confusing with the contract address, consider either adding something that mentions storage or changing to key.
___
*[website/docs/DataAvailability/on-chain-data.md, line 26 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMporq1ED9jXsk4JTm:-MwMporq1ED9jXsk4JTn:b-jrsk18) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L26)):*
> ```Markdown
>     * `value` - the new value
> 
> ## Example
> ```

Add a sentence before or after the JSON that explains what are we going to do.
something like - "We give an example of the on-chain data of a specific state update and explain each element"



_Code quote:_
```Markdown
## Example
```
___
*[website/docs/DataAvailability/on-chain-data.md, line 27 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsqKADLemmYZWn0gO:-MwMsqKADLemmYZWn0gP:b-wxtozv) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L27)):*
> ```Markdown
> 
> ## Example
> ```json
> ```

Do we know of a way to add lines to this block code? It will make the explanation much clearer.
___
*[website/docs/DataAvailability/on-chain-data.md, line 99 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMpa_3CIySCBOuy2hQ:-MwMpa_3CIySCBOuy2hR:bdsdw64) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L99)):*
> ```Markdown
> ## Extract from Ethereum
> 
> The data described above is sent across several Etherum transactions, each holding a part of this array as calldata. Each new StarkNet block has its associated state diff transactions. You may find the code for extracting this data from Ethereum in [Pathfinder's repo](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/src/ethereum/state_update/retrieve.rs). Pathfinder is the first StarkNet full node implementation, whose alpha version is planned for the begininnig of March 2022. You may also take a look at the [python script](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/resources/fact_retrieval.py) which extracts the same information.
> ```

Ethereum



_Code quote:_
```Markdown
Etherum
```
___
*[website/docs/DataAvailability/on-chain-data.md, line 99 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMpkYx4Xs_oDosazxU:-MwMpkYx4Xs_oDosazxV:b-w8jurs) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L99)):*
> ```Markdown
> ## Extract from Ethereum
> 
> The data described above is sent across several Etherum transactions, each holding a part of this array as calldata. Each new StarkNet block has its associated state diff transactions. You may find the code for extracting this data from Ethereum in [Pathfinder's repo](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/src/ethereum/state_update/retrieve.rs). Pathfinder is the first StarkNet full node implementation, whose alpha version is planned for the begininnig of March 2022. You may also take a look at the [python script](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/resources/fact_retrieval.py) which extracts the same information.
> ```

beginning



_Code quote:_
```Markdown
begininnig
```
___
*[website/docs/DataAvailability/on-chain-data.md, line 99 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMt3Mn60-or4fWt_op:-MwMt3Mn60-or4fWt_oq:b7tw91x) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L99)):*
> ```Markdown
> ## Extract from Ethereum
> 
> The data described above is sent across several Etherum transactions, each holding a part of this array as calldata. Each new StarkNet block has its associated state diff transactions. You may find the code for extracting this data from Ethereum in [Pathfinder's repo](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/src/ethereum/state_update/retrieve.rs). Pathfinder is the first StarkNet full node implementation, whose alpha version is planned for the begininnig of March 2022. You may also take a look at the [python script](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/resources/fact_retrieval.py) which extracts the same information.
> ```

Please remove mentions of specific dates in the docs.



_Code quote:_
```Markdown
, whose alpha version is planned for the begininnig of March 2022.
```

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/1)* status: all files reviewed, 17 unresolved discussions (waiting on @bbrandtom)

___
*[website/docs/DataAvailability/on-chain-data.md, line 3 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMruX5-drqteXNj_TX:-Mwg9Wn103LoxK67e5an:b-7kadrq) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L3)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Missing what is explained in this section - we explain here the format of the calldata that is posted on L1.
</blockquote></details>

It's under introduction, my goal is to explain WHAT is on chain data

** I comment here but whenever I'll fix, I'll do it in the new PR and comment there myself, so we can continue the discussion there after I edit.
___
*[website/docs/DataAvailability/on-chain-data.md, line 7 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMrdZ5AyGpOUWgj67t:-Mwg9uLQ74E2SKkKF417:b-qb5fl7) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L7)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Not sure exactly what you're trying to say in this paragraph
</blockquote></details>

Same as bove
___
*[website/docs/DataAvailability/on-chain-data.md, line 11 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMs5Ka778GA6YAKj8E:-MwgAXUX5EH-ZbA6eMdu:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L11)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

that - >and
</blockquote></details>

Done.
___
*[website/docs/DataAvailability/on-chain-data.md, line 11 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsADy2I6nNKGW_J28:-MwgAvtT3K79Pml6RMHF:b-uxqyr3) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L11)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

remove double space
</blockquote></details>

what double space?
___
*[website/docs/DataAvailability/on-chain-data.md, line 13 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsDOX1Zh5CScTWCa7:-MwgFw746wLQioGsxnGH:bfieatm) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L13)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I suggest giving a name to each variable - not clear when a name is given and when not.
Also, do those names reflect something in the code?
</blockquote></details>


Which code? there's our python script and Pathfinder's rust, they might be loosely connected to the former but are used here for demonstrative purposes
I didn't name it as it's literally the number of cells in the array 
___
*[website/docs/DataAvailability/on-chain-data.md, line 17 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsPxP2IdXqLolfu26:-MwgBV8m1nqaT600iX9O:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L17)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

missing "the" at the beginning of the sentence,
same belown
</blockquote></details>

Done.
___
*[website/docs/DataAvailability/on-chain-data.md, line 18 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMpULYAEwJ0NyTMdbq:-MwgBotI3QT3ZM6oB7EN:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L18)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

`call_data`
or change to `calldata` above

Also, consider changing to something that reflects the fact it is the ctr arguments, as calldata is generic to all of the data that is being sent on L1.
</blockquote></details>

Done.
___
*[website/docs/DataAvailability/on-chain-data.md, line 18 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsWRK2AcLvB9547Pq:-MwgC5iI-r7Z3kEcsrjq:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L18)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

constructors - constructor
</blockquote></details>

Done.
___
*[website/docs/DataAvailability/on-chain-data.md, line 19 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMpRDb2Si5SHWcFzlw:-MwgCExzEige3tqYEYgM:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L19)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

storage
</blockquote></details>

Done.
___
*[website/docs/DataAvailability/on-chain-data.md, line 20 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMs_fj-ollveLouG-d:-MwgCu-D1uwdqhJAMcl0:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L20)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I think we are missing the address here
</blockquote></details>

Done.
___
*[website/docs/DataAvailability/on-chain-data.md, line 23 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMpSv00WTQExq5bhhf:-MwgDJ6y7AJoMCHOuixk:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L23)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

storage
</blockquote></details>

Done.
___
*[website/docs/DataAvailability/on-chain-data.md, line 23 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMseCw-xqqHj8UFgyd:-MwgDukx1oUNuH57cEcc:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L23)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Do we call this address? I think it is a bit confusing with the contract address, consider either adding something that mentions storage or changing to key.
</blockquote></details>

Done.
___
*[website/docs/DataAvailability/on-chain-data.md, line 26 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMporq1ED9jXsk4JTm:-MwgEeJ90kwPnKu3advi:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L26)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Add a sentence before or after the JSON that explains what are we going to do.
something like - "We give an example of the on-chain data of a specific state update and explain each element"
</blockquote></details>

Done.
___
*[website/docs/DataAvailability/on-chain-data.md, line 27 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsqKADLemmYZWn0gO:-MwgEft6457C5CUkWIj6:bai9ify) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L27)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Do we know of a way to add lines to this block code? It will make the explanation much clearer.
</blockquote></details>

No, I will ping Dan again about it
___
*[website/docs/DataAvailability/on-chain-data.md, line 99 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMpa_3CIySCBOuy2hQ:-MwgF0yS4c7GClXc9INS:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L99)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Ethereum
</blockquote></details>

Done.
___
*[website/docs/DataAvailability/on-chain-data.md, line 99 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMpkYx4Xs_oDosazxU:-MwgFN8q5TnU65-CItA3:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L99)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

beginning
</blockquote></details>

Done.
___
*[website/docs/DataAvailability/on-chain-data.md, line 99 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMt3Mn60-or4fWt_op:-MwgFkos2RQ9aUe4TNmT:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L99)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Please remove mentions of specific dates in the docs.
</blockquote></details>

Done.

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/1)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[website/docs/DataAvailability/on-chain-data.md, line 3 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMruX5-drqteXNj_TX:-MwgNk6pDXrR66r0D4Ef:bewk4s) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L3)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

It's under introduction, my goal is to explain WHAT is on chain data

** I comment here but whenever I'll fix, I'll do it in the new PR and comment there myself, so we can continue the discussion there after I edit.
</blockquote></details>

just to make sure - you intend to add what is the goal, or are you saying you think it's clear enough as is?
___
*[website/docs/DataAvailability/on-chain-data.md, line 11 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsADy2I6nNKGW_J28:-MwgNAs_7AR3trIEy1F1:b-lban9r) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L11)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

what double space?
</blockquote></details>

between "that is" and "encoded"
___
*[website/docs/DataAvailability/on-chain-data.md, line 13 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsDOX1Zh5CScTWCa7:-MwgNL8w0OzXMslzwUIJ:b-y6rquy) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L13)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>


Which code? there's our python script and Pathfinder's rust, they might be loosely connected to the former but are used here for demonstrative purposes
I didn't name it as it's literally the number of cells in the array 
</blockquote></details>

you're right, forget the question about the code.
I still think it will be easier to have a var name, but it's non-blocking.

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/1)* status: all files reviewed, 3 unresolved discussions (waiting on @bbrandtom)

___
*[website/docs/DataAvailability/on-chain-data.md, line 3 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMruX5-drqteXNj_TX:-MwtmLcR3xhsmMfnTqLQ:bd4dy5j) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L3)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

just to make sure - you intend to add what is the goal, or are you saying you think it's clear enough as is?
</blockquote></details>

I intended to add what is the goal
___
*[website/docs/DataAvailability/on-chain-data.md, line 11 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/1#-MwMsADy2I6nNKGW_J28:-Mwtmmk0BjhR6xdwI_nl:b-n1j6l4) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/36109f5c71f94c81e2ac12b83abdd710249a46fa/website/docs/DataAvailability/on-chain-data.md#L11)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

between "that is" and "encoded"
</blockquote></details>

I see, already done in another fix

**Review by bbrandtom — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request closed without merging**
