### PR TITLE
docs: minor 0.8.2 updates

### PR DESCRIPTION
**Pull request by ArielElp**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] Docs have been updated
- [ ] PR title is follow the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

---
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/29)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/29)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`docs/Blocks/header.md` line 16 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-N1lfKrcDe92dXib_5f2:-N1lfKrcDe92dXib_5f3:bmslka9) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/005abfebbe808a1f78cf5c4520b4b52dc5413b39/docs/Blocks/header.md#L16)):*
> ```Markdown
> | ------------------------ | -------------- | --------------------------------------------------------------------------------- | :----------------: |
> | `parent_block_hash`      | `FieldElement` | The hash of this block's parent                                                   | :heavy_check_mark: |
> | `block_number`           | `Integer`      | The number (height) of this block                                                 | :heavy_check_mark: |
> ```

I think we added it to cover the case where you ask about the pending block, and then you don't have a number but pending?
Am I missing something here?
___
*[`docs/Blocks/header.md` line 18 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-N1lfe6T51fvHENodP_6:-N1lfe6T51fvHENodP_7:bd30ifx) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/005abfebbe808a1f78cf5c4520b4b52dc5413b39/docs/Blocks/header.md#L18)):*
> ```Markdown
> | `block_number`           | `Integer`      | The number (height) of this block                                                 | :heavy_check_mark: |
> | `global_state_root`      | `FieldElement` | The state [commitment](../State/starknet-state#state-commitment) after this block | :heavy_check_mark: |
> | `sequencer_address`      | `FieldElement` | The StarkNet address of the sequencer who created this block                      | :heavy_check_mark: |
> ```

good catch
___
*[`docs/CLI/commands.md` line 145 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-N1lfrAJ0Seh96yOmJFT:-N1lfrAKAHlPtI0nWi2K:b-5q0kki) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/005abfebbe808a1f78cf5c4520b4b52dc5413b39/docs/CLI/commands.md#L145)):*
> ```Markdown
> - `nonce` - account nonce, only relevant if the call is going through an account
> 
> :::info Block Tag
> ```

Why is it here? Maybe it should be part of the comments at the top of the page?
___
*[`docs/L1<>L2 Communication/token-bridge.md` line 60 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-N1lgAjC2xhisn0YyJAr:-N1lgAjC2xhisn0YyJAs:bg88hq5) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/005abfebbe808a1f78cf5c4520b4b52dc5413b39/docs/L1%3C%3EL2%20Communication/token-bridge.md#L60)):*
> ```Markdown
> | Token | Max deposit | Max total value locked |
> | ----- | ----------- | ---------------------- |
> | ETH   | 0.025 Eth   | 50 Eth                 |
> ```

revert and I will do it in a different PR to make it faster

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/29)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @bbrandtom)

___
*[`docs/Blocks/header.md` line 16 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-N1lfKrcDe92dXib_5f2:-N1lgR4oArVRPgsn_y5L:b-jxhcwm) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/005abfebbe808a1f78cf5c4520b4b52dc5413b39/docs/Blocks/header.md#L16)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I think we added it to cover the case where you ask about the pending block, and then you don't have a number but pending?
Am I missing something here?
</blockquote></details>

This is the block header, not API docs
___
*[`docs/Blocks/header.md` line 18 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-N1lfe6T51fvHENodP_6:-N1lgNqy5dmVRTuClaDL:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/005abfebbe808a1f78cf5c4520b4b52dc5413b39/docs/Blocks/header.md#L18)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

good catch
</blockquote></details>

Done.
___
*[`docs/CLI/commands.md` line 145 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-N1lfrAJ0Seh96yOmJFT:-N1lgZTWE2eL_0LyDhmC:b-2k0ldf) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/005abfebbe808a1f78cf5c4520b4b52dc5413b39/docs/CLI/commands.md#L145)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Why is it here? Maybe it should be part of the comments at the top of the page?
</blockquote></details>

below the fist method that is using it, I can move it just after the parameter
___
*[`docs/L1<>L2 Communication/token-bridge.md` line 60 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-N1lgAjC2xhisn0YyJAr:-N1lgiAa0qqBKISnZgua:bdah1cy) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/005abfebbe808a1f78cf5c4520b4b52dc5413b39/docs/L1%3C%3EL2%20Communication/token-bridge.md#L60)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

revert and I will do it in a different PR to make it faster
</blockquote></details>

It won't conflict, we can merge this in a sec

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/29)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`docs/Blocks/header.md` line 16 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-N1lfKrcDe92dXib_5f2:-N1lh42BDe3ZF0qUOSLE:b-7jzv7t) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/005abfebbe808a1f78cf5c4520b4b52dc5413b39/docs/Blocks/header.md#L16)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

This is the block header, not API docs
</blockquote></details>

right
___
*[`docs/Blocks/header.md` line 18 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-N1lfe6T51fvHENodP_6:-N1lh7-H-_FX4dFAcxXD:b-fn8mpi) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/005abfebbe808a1f78cf5c4520b4b52dc5413b39/docs/Blocks/header.md#L18)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:facepalm: 
___
*[`docs/CLI/commands.md` line 145 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-N1lfrAJ0Seh96yOmJFT:-N1lhLLk-um-oSS1QDUF:b-s5quhz) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/005abfebbe808a1f78cf5c4520b4b52dc5413b39/docs/CLI/commands.md#L145)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

below the fist method that is using it, I can move it just after the parameter
</blockquote></details>

When I want to see how to use a specific method, I'm not guaranteed to move through this method, so I might miss this info. So either we link from every "tag" to this info, or we put it on the top.

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/29)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @bbrandtom)

___
*[`docs/CLI/commands.md` line 145 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-N1lfrAJ0Seh96yOmJFT:-N1lnBmo0zArv2TizI21:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/005abfebbe808a1f78cf5c4520b4b52dc5413b39/docs/CLI/commands.md#L145)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

When I want to see how to use a specific method, I'm not guaranteed to move through this method, so I might miss this info. So either we link from every "tag" to this info, or we put it on the top.
</blockquote></details>

Done.

**Review by bbrandtom — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/29#-:-N1lnlhY1DJnAr71X-Gq:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
