### PR TITLE
dos: deployment fee

### PR DESCRIPTION
**Pull request by ArielElp**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] Docs have been updated
- [ ] PR title is follow the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

---
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/37)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/37)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @stoobie)

___
*[`docs/Fees/fee-mechanism.md` line 163 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/37#-N3ZJC2Y2QQoGKe4fG3v:-N3ZJC2Y2QQoGKe4fG3w:b-pawz94) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/350ca8106805bc61d428bf966ce46ab36a3fd685/docs/Fees/fee-mechanism.md#L163)):*
> ```Markdown
> The fee is charged atomically with the transaction execution on L2. The StarkNet OS injects a transfer of the fee-related ERC-20, with an amount equal to the fee paid, sender equals to the transaction submitter, and the sequencer as a receiver.
> 
> 
> ```

remove this line and verify that there are no other TODO related to v0.9.0

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/37)* status: all files reviewed, 1 unresolved discussion (waiting on @bbrandtom and @stoobie)

___
*[`docs/Fees/fee-mechanism.md` line 163 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/37#-N3ZJC2Y2QQoGKe4fG3v:-N3Zkq9k9KmwdBQ77eRV:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/350ca8106805bc61d428bf966ce46ab36a3fd685/docs/Fees/fee-mechanism.md#L163)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

remove this line and verify that there are no other TODO related to v0.9.0
</blockquote></details>

Done.

**Review by bbrandtom — COMMENTED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/37#-:-N3dEfqf0k5Ea4bK0XrA:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @bbrandtom and @stoobie)

**Review by bbrandtom — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/37)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stoobie)

**Pull request merged**
