### PR TITLE
feat: ltu front page design updates

### PR DESCRIPTION
**Pull request by georgeLtu**
front page design updates

---
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/24)

### CODE REVIEW

**Comment by stoobie** [comment]
@georgeLtu 
The text in the left nav should be black. Right now it appears greyed out, as if all topics have already been viewed, and on top of that, it's difficult to see the text at all:
image

**Comment by stoobie** [comment]
The footer takes up too much space. This doesn't appear to be an issue on the main page, but when I'm viewing the Introduction document, this is very much an issue.

**Comment by stoobie** [comment]
@georgeLtu @ArielElp  These are UX issues, not graphic design, but I'm adding them here so the comments are captured: 
1. The first square says "What is StarkNet?" as if that's the title of the document. When I click on it, I see *Introduction*. Immediately following **Introduction** it says **What is StarkNet** as a section heading. Need to fix this.
2. Change **Introduction** to **What is StarkNet**.
3. The link **Technical Documentation** at the top goes to the same *Introduction* document. Need to fix this. This link should be the home page.
4. The StarkNet logo at the top should go to https://starknet.io
5. Can we add or remove squares according to our needs? There are only three documents on this page, but there are five squares. The Block explorer is not a document, and the Latest Updates is not owned or controlled by us.

**Comment by georgeLtu** [comment]
@stoobie 

1. fixed
2. fixed
3. fixed
4. fixed
5. if you know how to control ﻿docusaurus, you can control it, if you need our help please update us

**Review by ArielElp — CHANGES_REQUESTED** [review]
re the footer size, this looks ok on a 27'' screen, but weird on my 13'' mac
Also, let's delete the StarkNet logo from the footer



> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/24#-:-N2MH_PXCHfzfrczzbed:b-fzc54c)* status: 1 of 16 files reviewed, 2 unresolved discussions (waiting on @dan-ziv and @georgeLtu)

___
*[`src/components/HomepageCard/HomepageCard.js` line 87 at r2](https://reviewable.io/reviews/starkware-libs/starknet-docs/24#-N2MGoDS-efgvY4oTLsN:-N2MGoDS-efgvY4oTLsO:b-c4hex) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/1e47c4f1dfa0e4331ecd4ef8c9802e1001bdc8c3/src/components/HomepageCard/HomepageCard.js#L87)):*
> ```JavaScript
>           }
>         >
>           Explore Blocks
> ```

remove those from cards
___
*[`src/config/home.json` line 5 at r2](https://reviewable.io/reviews/starkware-libs/starknet-docs/24#-N2MJTi9Dqg7QyZs74l3:-N2MJTi9Dqg7QyZs74l4:bphc0h) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/1e47c4f1dfa0e4331ecd4ef8c9802e1001bdc8c3/src/config/home.json#L5)):*
> ```JSON
>     "linkName": "docs/Intro",
>     "img": "1.svg",
>     "title": "What is StarkNet?",
> ```

Align this text between different cards (card title should be on the same level for all boxes, see e.g. my screenshot above)

**Pull request closed without merging**
